language: php

sudo: false

php:
    - 7.1

before_script:
    - composer self-update
    - composer install --prefer-dist --no-interaction
    - mkdir -p data/install/logs
    - chmod -R 777 data/install/logs

script:
    - vendor/bin/codecept run --coverage-xml
    - vendor/bin/phpstan analyse src/ -l 7 -c phpstan.neon
    - vendor/bin/phpcs src -v -s --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml
    - vendor/bin/phpcs tests -v -s --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml

notifications:
    email: false

after_success:
    - travis_retry php vendor/bin/coveralls
