language: php

sudo: false

php:
    - 7.2

before_script:
    - composer install --prefer-dist --no-interaction

script:
    - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src/
    - vendor/bin/phpcs -v -s --standard=vendor/spryker/code-sniffer/Spryker/ruleset.xml src/ tests/
    - vendor/bin/codecept run --coverage-xml

notifications:
    email: false

after_success:
    - travis_retry php vendor/bin/coveralls
